# Generated by Django 5.2.17 on 2026-09-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ficha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("profissao", models.CharField(max_length=50)),
                ("vida", models.IntegerField(default=0)),
                ("forca", models.IntegerField(default=0)),
                ("destreza", models.IntegerField(default=0)),
                ("agilidade", models.IntegerField(default=0)),
                ("inteligencia", models.IntegerField(default=0)),
                ("sabedoria", models.IntegerField(default=0)),
                ("carisma", models.IntegerField(default=0)),
                ("labia", models.IntegerField(default=0)),
                ("percepcao", models.IntegerField(default=0)),
                ("intuicao", models.IntegerField(default=0)),
                ("fe", models.IntegerField(default=0)),
                ("status_especiais", models.TextField(blank=True, null=True)),
                ("status_religiosos", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
