# Generated by Django 5.2.17 on 2026-09-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ficha",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
