# Generated by Django 5.2.17 on 2026-09-09 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_ficha_imagem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ficha",
            name="religiao",
            field=models.CharField(
                choices=[
                    ("Hibirismo", "Hibirismo"),
                    ("Ateismo", "Ateismo"),
                    ("Agnosticismo", "Agnosticismo"),
                    ("Flowdiesto", "Flowdiesto"),
                    ("Zudelista", "Zudelista"),
                    ("Sanhismo", "Sanhismo"),
                    ("Cristianismo", "Cristianismo"),
                ],
                default="Agnosticismo",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ficha",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Ficha",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
